### ISSUE TITLE
Add panel to display robot addresses and show if they are connected

### ISSUE THREAD

**Issue by ryanjmarcotte** [utdrobotchess/chess-game#1]
@ohasangit is this done?

**Comment by Dzurpaladin** [comment]
Lots of spam how do i disenroll this email chain


-------- Original message --------

**Comment by ryanjmarcotte** [comment]
This is not spam. You are following our repository, so you are receiving
emails as issues are reported. Change your notification settings on Github
- there is nothing we can do to change that for you.

**Comment by ohasangit** [comment]
Finished this with the last commit
